config/urls.py
# config/urls.py

# Django modules
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    # accounts
    # path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('accounts/', include('apps.accounts.urls')),
    # newsmag
    path('', include('apps.newsmag.urls', namespace='newsmag')),
    # admin
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/newsmag/models.py
# apps/newsmbag/models.py

# Django modules
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.

# MODEL:Category
class Category(models.Model):

    STATUS_CATEGORY_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    name = models.CharField(max_length=255)
    slug  = models.SlugField(max_length=255, verbose_name='Url', unique=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status  = models.CharField(max_length=10, choices=STATUS_CATEGORY_CHOICES, default='draft')

    def __str__(self):
        return self.name
        
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ['name']

templates/shared/admin/footer.html
{% load static %}

                                <div class="submit-row">
                                    <input type="submit" value="Save" class="default" name="_save">
                                    <input type="submit" value="Save and add another" name="_addanother">
                                    <input type="submit" value="Save and continue editing" name="_continue">
                                </div>
                                <script id="django-admin-form-add-constants" src="{% static 'admin/js/change_form.js' %}" data-model-name="category" async></script>
                                <script id="django-admin-prepopulated-fields-constants"src="{% static 'admin/js/prepopulate_init.js' %}"data-prepopulated-fields="[{&quot;id&quot;: &quot;#id_slug&quot;, &quot;name&quot;: &quot;slug&quot;, &quot;dependency_ids&quot;: [&quot;#id_name&quot;], &quot;dependency_list&quot;: [&quot;name&quot;], &quot;maxLength&quot;: 255, &quot;allowUnicode&quot;: false}]"></script>
                            </div>
                        </form>
                        <!-------------------- END FORM -------------------->
                    </div>
                    <br class="clear">
                </div>
                <!-- END Content -->
                <div id="footer"></div>
            </div>
        </div>
    </div>
    <!-- END Container -->
</body>
</html>

templates/shared/admin/head.html
{% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/nav_sidebar.css' %}">
    <script src="{% static 'admin/js/nav_sidebar.js' %}" defer></script>
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}">
    <script src="/admin/jsi18n/"></script>
    <script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    <script src="{% static 'admin/js/calendar.js' %}"></script>
    <script src="{% static 'admin/js/jquery.init.js' %}"></script>
    <script src="{% static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>
    <script src="{% static 'admin/js/core.js' %}"></script>
    <script src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
    <script src="{% static 'admin/js/actions.js' %}"></script>
    <script src="{% static 'admin/js/urlify.js' %}"></script>
    <script src="{% static 'admin/js/prepopulate.js' %}"></script>
    <script src="{% static 'admin/js/vendor/xregexp/xregexp.js' %}"></script>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/responsive.css' %}">
    <meta name="robots" content="NONE,NOARCHIVE">